spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

google:
  ai:
    key: ${GOOGLE_API_KEY}
